### ISSUE TITLE
ブラウザ横幅によってホーム画面のカード表示が崩れる

### ISSUE THREAD

**Issue by 07JP27** [Scout-Association-of-Japan/SAJ-DownloadCenter#26]
## 起こっている問題 / The Problem
- ホーム画面のカード表示が崩れる

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/11060273/87532846-b4f8fa80-c6ce-11ea-9f04-eb2b7d83e228.png)

## 期待する見せ方・挙動 / Expected Behavior
- カードが整列している状態。

## 起こっている問題の再現手段 / Steps to Reproduce
1. Windows & Chromeでホーム画面を開きブラウザの横幅を変える
※上記環境以外は未確認

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by kazuemon** [comment]
各カードのタイトルを改行されないようにする(無理にはみ出させる)か、 Flexbox・CSS Grid 等でグリッドレイアウトを作り直すかですね...

## 比較

※「保護者インタビュー【ショートVer】」にのみ適用
 
- `overflow-wrap: break-word;` (現在)
![image](https://user-images.githubusercontent.com/12812934/96597641-04cc0b00-1329-11eb-856f-e2a0a7101ec6.png)

- `white-space: nowrap;` に変更
![image](https://user-images.githubusercontent.com/12812934/96597717-1ca38f00-1329-11eb-81ad-61506f2bc2d6.png)

- さらに `overflow: hidden;` を追加
![image](https://user-images.githubusercontent.com/12812934/96597685-144b5400-1329-11eb-9224-abae4697c8ae.png)

**Comment by 07JP27** [comment]
@kazuemon 
検証ありがとうございます！
1行固定にする場合オーバーした部分はtext-overflowで「…」表記にするとかですかね。
https://developer.mozilla.org/ja/docs/Web/CSS/text-overflow

**Comment by kazuemon** [comment]
@07JP27 
こういう感じですかね?
```css
.thumbnail-box a span {
    display: block;
    padding: 0 10px 10px 10px;
    overflow: hidden;
    color: black;
    font-weight: 500;
    font-size: 1em;
    text-align: center;
    white-space: nowrap;
    text-overflow: ellipsis;
}
```
![image](https://user-images.githubusercontent.com/12812934/96724950-53da7480-13eb-11eb-9901-d02e415aae5f.png)
![image](https://user-images.githubusercontent.com/12812934/96724930-4e7d2a00-13eb-11eb-841a-e179735dc9b1.png)
